### PR TITLE
add conditional tu buttons on homepage

### PR DESCRIPTION
**Pull request by mixcas**

### CODE REVIEW

**Comment by mixcas** [comment]
MMMM if im a returning user with an existing account but not logged in its kinda confusing

**Comment by mixcas** [comment]
whatcha think @varffs ?

**Comment by varffs** [comment]
Yh thats why my suggestion was only to make the second link conditional. That would make ux sense I think. Either link to the application or to login.

**Comment by mixcas** [comment]
It doesn't make too much sense to me to make the second link conditional. Makes more sense to me to make the first one conditional

This are the cases:
- No account - Not logged: Both links
- Account - Not logged: Both links
- Account - Logged: Only second link

**Pull request merged**
